{
  user(login: "oke-py") {
    contributionsCollection(from: "2019-01-01T00:00:00.000Z", to: "2019-12-31T23:59:59.000Z") {
      commitContributionsByRepository {
        contributions {
          totalCount
        }
        repository {
          nameWithOwner
        }
      }
      issueContributionsByRepository {
        contributions {
          totalCount
        }
        repository {
          nameWithOwner
        }
      }
      pullRequestContributionsByRepository {
        contributions {
          totalCount
        }
        repository {
          nameWithOwner
        }
      }
      pullRequestReviewContributionsByRepository {
        contributions {
          totalCount
        }
        repository {
          nameWithOwner
        }
      }
    }
  }
}
